version: '3.8'
services:
  webapp:
    build: .
    ports:
      - "5056:80"
    environment:
      - ConnectionStrings__OrgCatDb=Host=db;Database=orgcat;Username=postgres;Password=asdfoot
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asdfoot
      - POSTGRES_DB=orgcat
